---
deployment:
  tasks:
    - export DEPLOYPATH=/home/banb4683/public_html/
    - /usr/local/bin/composer install --no-dev --prefer-dist --optimize-autoloader || true
    - /bin/cp -R . $DEPLOYPATH
    - /bin/chmod -R 755 $DEPLOYPATH/storage $DEPLOYPATH/bootstrap/cache || true
