---
deployment:
  tasks:
    - export DEPLOYPATH=/home/banb4683/public_html/
    - composer install --no-dev --optimize-autoloader
    - php artisan config:clear || true
    - php artisan route:clear || true
    - php artisan cache:clear || true
    - php artisan config:cache
    - php artisan route:cache
    - chmod -R 775 storage bootstrap/cache || true
    - /bin/rsync -av --delete \
        --exclude=".git" \
        --exclude=".cpanel.yml" \
        --exclude="node_modules" \
        --exclude=".env" \
        ./ $DEPLOYPATH
